### ISSUE TITLE
testing platform

### ISSUE THREAD

**Issue by sinanshi** [UCL/gp_emulator#10]
Potential unit test functions:
1. cdist
2. element wise matrix multiplication
3. element wise matrix plus
4. sure the whole predictor at the end.

**Comment by sinanshi** [comment]
I don't know what is the best testing platform for such a python cuda program. I will say the most useful testing strategy can be validating the CUDA routines by the result of corresponding python ones. In such a test, we can do benchmarking for both python and GPU.  However  calling C by python per test, I'm afraid there will be a lot of work to do. 

Is there any suggestion for a testing platform that is tidy and relatively easy to use? pytest will be good?

**Comment by mdavezac** [comment]
If you want to test python against C, then using [Cython](http://docs.cython.org/index.html) with pytest is probably the way to go. You can use our [cmake recipes](https://github.com/UCL/GreatCMakeCookOff/wiki/Creating-python-packages) to create python/cython packages and [test them relatively easily](https://github.com/UCL/GreatCMakeCookOff/blob/master/scripts/AddPyTest.cmake). E.g. in some `CMakelists.txt`

``` cmake
add_pytest(this_cython_file.pyx that_python_file.py)
```

However, it might be easier to just stick to ne language at a time

**Comment by sinanshi** [comment]
I would like to stick on the original python and C, since for learning again cython may cost too much time for me. Do you think pytest can do it well even without cythyon. Sure there gonna be a lot of extra work to do. Do you think it is still durable?

**Comment by jenshnielsen** [comment]
@sinanshi cython can be used to wrap c code http://docs.cython.org/src/userguide/external_C_code.html
in addition to writing cython code.
