### ISSUE TITLE
testings are not consistent with single and double precision.

### ISSUE THREAD

**Issue by sinanshi** [UCL/gp_emulator#34]
Testing data are produced by double precision input data and trancated to single precision afterward. It is not a good indication. What am I going to change is:
1. change input data of python function
2. feed python function by double, compare the result only with predict(). Instead of comparing results, we need set a threashold for some other indicators, such as rnorm.

**Comment by jamespjh** [comment]
When you close an issue, you should put a note saying why, e.g. completed, gave up, etc.

**Comment by sinanshi** [comment]
done.
